import os
import sys
from src.exceptions import CustomException
from src.logger import logging
from src.utils import save_object

import numpy as np
import pandas as pd
from dataclasses import dataclass

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,StandardScaler

@dataclass
class DataTransformationConfig:
    preprocessor_obj_file_path:str = os.path.join('artifacts', 'preprocessor.pkl')

class DataTransformation:
    def __init__(self):
        self.data_transformation_config = DataTransformationConfig()

    def get_data_transformer_object(self):
        ''' This Function is responsible for data transformation.
        '''

        try:
            numerical_columns = ['Rating', 'Number of ratings','Price']
            categorical_columns = ['Category']
            binary_encoded_columns = ['Default : Access DRM content. (S)',
                                    'Default : Access Email provider data (S)',
                                    'Default : Access download manager. (S)',
                                    'Default : Advanced download manager functions. (S)',
                                    'Default : Audio File Access (S)',
                                    'Default : Install DRM content. (S)',
                                    'Default : Modify Google settings (S)',
                                    'Default : Move application resources (S)',
                                    'Default : Read Google settings (S)',
                                    'Default : Send download notifications. (S)',
                                    'Default : Voice Search Shortcuts (S)',
                                    'Default : access SurfaceFlinger (S)',
                                    'Default : access checkin properties (S)',
                                    'Default : access the cache filesystem (S)',
                                    'Default : bind to a wallpaper (S)',
                                    'Default : bind to an input method (S)',
                                    'Default : change screen orientation (S)',
                                    'Default : control location update notifications (S)',
                                    'Default : control system backup and restore (S)',
                                    'Default : delete applications (S)',
                                    "Default : delete other applications' caches (S)",
                                    "Default : delete other applications' data (S)",
                                    'Default : directly call any phone numbers (S)',
                                    'Default : directly install applications (S)',
                                    'Default : disable or modify status bar (S)',
                                    'Default : display unauthorized windows (S)',
                                    'Default : enable or disable application components (S)',
                                    'Default : force application to close (S)',
                                    'Default : force device reboot (S)',
                                    'Default : interact with a device admin (S)',
                                    'Default : manage application tokens (S)',
                                    'Default : modify battery statistics (S)',
                                    'Default : modify secure system settings (S)',
                                    'Default : modify the Google services map (S)',
                                    'Default : monitor and control all application launching (S)',
                                    'Default : partial shutdown (S)',
                                    'Default : permission to install a location provider (S)',
                                    'Default : power device on or off (S)',
                                    'Default : press keys and control buttons (S)',
                                    'Default : prevent app switches (S)',
                                    'Default : read frame buffer (S)',
                                    'Default : read phone state and identity (S)',
                                    'Default : record what you type and actions you take (S)',
                                    'Default : set time (S)',
                                    'Default : update component usage statistics (S)',
                                    'Development tools : enable application debugging (D)',
                                    'Development tools : limit number of running processes (D)',
                                    'Development tools : make all background applications close (D)',
                                    'Development tools : send Linux signals to applications (D)',
                                    'Hardware controls : change your audio settings (D)',
                                    'Hardware controls : control flashlight (S)',
                                    'Hardware controls : control vibrator (S)',
                                    'Hardware controls : record audio (D)',
                                    'Hardware controls : take pictures and videos (D)',
                                    'Hardware controls : test hardware (S)',
                                    'Network communication : Broadcast data messages to applications. (S)',
                                    'Network communication : control Near Field Communication (D)',
                                    'Network communication : create Bluetooth connections (D)',
                                    'Network communication : full Internet access (D)',
                                    'Network communication : make/receive Internet calls (D)',
                                    'Network communication : receive data from Internet (S)',
                                    'Network communication : view Wi-Fi state (S)',
                                    'Network communication : view network state (S)',
                                    'Phone calls : intercept outgoing calls (D)',
                                    'Phone calls : modify phone state (S)',
                                    'Phone calls : read phone state and identity (D)',
                                    'Services that cost you money : directly call phone numbers (D)',
                                    'Services that cost you money : send SMS messages (D)',
                                    'Storage : modify/delete USB storage contents modify/delete SD card contents (D)',
                                    'System tools : allow Wi-Fi Multicast reception (D)',
                                    'System tools : automatically start at boot (S)',
                                    'System tools : bluetooth administration (D)',
                                    'System tools : change Wi-Fi state (D)',
                                    'System tools : change network connectivity (D)',
                                    'System tools : change your UI settings (D)',
                                    'System tools : delete all application cache data (D)',
                                    'System tools : disable keylock (D)',
                                    'System tools : display system-level alerts (D)',
                                    'System tools : expand/collapse status bar (S)',
                                    'System tools : force stop other applications (S)',
                                    'System tools : format external storage (D)',
                                    'System tools : kill background processes (S)',
                                    'System tools : make application always run (D)',
                                    'System tools : measure application storage space (S)',
                                    'System tools : modify global animation speed (D)',
                                    'System tools : modify global system settings (D)',
                                    'System tools : mount and unmount filesystems (D)',
                                    'System tools : prevent device from sleeping (D)',
                                    'System tools : read subscribed feeds (S)',
                                    'System tools : read sync settings (S)',
                                    'System tools : read sync statistics (S)',
                                    'System tools : read/write to resources owned by diag (S)',
                                    'System tools : reorder running applications (D)',
                                    'System tools : retrieve running applications (D)',
                                    'System tools : send package removed broadcast (S)',
                                    'System tools : send sticky broadcast (S)',
                                    'System tools : set preferred applications (S)',
                                    'System tools : set time zone (D)',
                                    'System tools : set wallpaper (S)',
                                    'System tools : set wallpaper size hints (S)',
                                    'System tools : write Access Point Name settings (D)',
                                    'System tools : write subscribed feeds (D)',
                                    'System tools : write sync settings (D)',
                                    'Your accounts : Google App Engine (D)',
                                    'Your accounts : Google Docs (D)',
                                    'Your accounts : Google Finance (D)',
                                    'Your accounts : Google Maps (D)',
                                    'Your accounts : Google Spreadsheets (D)',
                                    'Your accounts : Google Voice (D)',
                                    'Your accounts : Google mail (D)',
                                    'Your accounts : Picasa Web Albums (D)',
                                    'Your accounts : YouTube (D)',
                                    'Your accounts : YouTube usernames (D)',
                                    'Your accounts : access all Google services (S)',
                                    'Your accounts : access other Google services (D)',
                                    'Your accounts : act as an account authenticator (D)',
                                    'Your accounts : act as the AccountManagerService (S)',
                                    'Your accounts : contacts data in Google accounts (D)',
                                    'Your accounts : discover known accounts (S)',
                                    'Your accounts : manage the accounts list (D)',
                                    'Your accounts : read Google service configuration (S)',
                                    'Your accounts : use the authentication credentials of an account (D)',
                                    'Your accounts : view configured accounts (S)',
                                    'Your location : access extra location provider commands (S)',
                                    'Your location : coarse (network-based) location (D)',
                                    'Your location : fine (GPS) location (D)',
                                    'Your location : mock location sources for testing (D)',
                                    'Your messages : Read Email attachments (D)',
                                    'Your messages : Send Gmail (S)',
                                    'Your messages : edit SMS or MMS (D)',
                                    'Your messages : modify Gmail (D)',
                                    'Your messages : read Gmail (D)',
                                    'Your messages : read SMS or MMS (D)',
                                    'Your messages : read instant messages (D)',
                                    'Your messages : receive MMS (D)',
                                    'Your messages : receive SMS (D)',
                                    'Your messages : receive WAP (D)',
                                    'Your messages : send SMS-received broadcast (S)',
                                    'Your messages : send WAP-PUSH-received broadcast (S)',
                                    'Your personal information : add or modify calendar events and send email to guests (D)',
                                    'Your personal information : choose widgets (S)',
                                    "Your personal information : read Browser's history and bookmarks (D)",
                                    'Your personal information : read calendar events (D)',
                                    'Your personal information : read contact data (D)',
                                    'Your personal information : read sensitive log data (D)',
                                    'Your personal information : read user defined dictionary (D)',
                                    'Your personal information : retrieve system internal state (S)',
                                    'Your personal information : set alarm in alarm clock (S)',
                                    "Your personal information : write Browser's history and bookmarks (D)",
                                    'Your personal information : write contact data (D)',
                                    'Your personal information : write to user defined dictionary (S)']
            num_pipeline = Pipeline(steps =[('num_imputer',SimpleImputer(strategy = 'median')),
                                            ('scaler',StandardScaler(with_mean=False))])
            category_pipeline = Pipeline(steps= [('category_imputer',SimpleImputer(fill_value = '',strategy ='constant')),
                                                ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))])
            binary_pipeline = Pipeline(steps = [('binary_imputer',SimpleImputer(strategy='most_frequent'))])
            preprocessor = ColumnTransformer([('categorical',category_pipeline,categorical_columns),
                                              ('numerical',num_pipeline, numerical_columns),
                                              ('binary',binary_pipeline,binary_encoded_columns)])
            return preprocessor
        
        except Exception as e:
            raise CustomException(e,sys)
        
    def initiate_data_transformation(self, train_path, test_path):
        try:
            train_df = pd.read_csv(train_path)
            test_df = pd.read_csv(test_path)
            logging.info('Read train and test data')
            logging.info('preprocessing object instantiation started')
            preprocessor_object = self.get_data_transformer_object()
            numerical_columns = ['Rating', 'Number of ratings','Price']
            categorical_columns = ['Category']
            binary_encoded_columns = ['Default : Access DRM content. (S)',
                                    'Default : Access Email provider data (S)',
                                    'Default : Access download manager. (S)',
                                    'Default : Advanced download manager functions. (S)',
                                    'Default : Audio File Access (S)',
                                    'Default : Install DRM content. (S)',
                                    'Default : Modify Google settings (S)',
                                    'Default : Move application resources (S)',
                                    'Default : Read Google settings (S)',
                                    'Default : Send download notifications. (S)',
                                    'Default : Voice Search Shortcuts (S)',
                                    'Default : access SurfaceFlinger (S)',
                                    'Default : access checkin properties (S)',
                                    'Default : access the cache filesystem (S)',
                                    'Default : bind to a wallpaper (S)',
                                    'Default : bind to an input method (S)',
                                    'Default : change screen orientation (S)',
                                    'Default : control location update notifications (S)',
                                    'Default : control system backup and restore (S)',
                                    'Default : delete applications (S)',
                                    "Default : delete other applications' caches (S)",
                                    "Default : delete other applications' data (S)",
                                    'Default : directly call any phone numbers (S)',
                                    'Default : directly install applications (S)',
                                    'Default : disable or modify status bar (S)',
                                    'Default : display unauthorized windows (S)',
                                    'Default : enable or disable application components (S)',
                                    'Default : force application to close (S)',
                                    'Default : force device reboot (S)',
                                    'Default : interact with a device admin (S)',
                                    'Default : manage application tokens (S)',
                                    'Default : modify battery statistics (S)',
                                    'Default : modify secure system settings (S)',
                                    'Default : modify the Google services map (S)',
                                    'Default : monitor and control all application launching (S)',
                                    'Default : partial shutdown (S)',
                                    'Default : permission to install a location provider (S)',
                                    'Default : power device on or off (S)',
                                    'Default : press keys and control buttons (S)',
                                    'Default : prevent app switches (S)',
                                    'Default : read frame buffer (S)',
                                    'Default : read phone state and identity (S)',
                                    'Default : record what you type and actions you take (S)',
                                    'Default : set time (S)',
                                    'Default : update component usage statistics (S)',
                                    'Development tools : enable application debugging (D)',
                                    'Development tools : limit number of running processes (D)',
                                    'Development tools : make all background applications close (D)',
                                    'Development tools : send Linux signals to applications (D)',
                                    'Hardware controls : change your audio settings (D)',
                                    'Hardware controls : control flashlight (S)',
                                    'Hardware controls : control vibrator (S)',
                                    'Hardware controls : record audio (D)',
                                    'Hardware controls : take pictures and videos (D)',
                                    'Hardware controls : test hardware (S)',
                                    'Network communication : Broadcast data messages to applications. (S)',
                                    'Network communication : control Near Field Communication (D)',
                                    'Network communication : create Bluetooth connections (D)',
                                    'Network communication : full Internet access (D)',
                                    'Network communication : make/receive Internet calls (D)',
                                    'Network communication : receive data from Internet (S)',
                                    'Network communication : view Wi-Fi state (S)',
                                    'Network communication : view network state (S)',
                                    'Phone calls : intercept outgoing calls (D)',
                                    'Phone calls : modify phone state (S)',
                                    'Phone calls : read phone state and identity (D)',
                                    'Services that cost you money : directly call phone numbers (D)',
                                    'Services that cost you money : send SMS messages (D)',
                                    'Storage : modify/delete USB storage contents modify/delete SD card contents (D)',
                                    'System tools : allow Wi-Fi Multicast reception (D)',
                                    'System tools : automatically start at boot (S)',
                                    'System tools : bluetooth administration (D)',
                                    'System tools : change Wi-Fi state (D)',
                                    'System tools : change network connectivity (D)',
                                    'System tools : change your UI settings (D)',
                                    'System tools : delete all application cache data (D)',
                                    'System tools : disable keylock (D)',
                                    'System tools : display system-level alerts (D)',
                                    'System tools : expand/collapse status bar (S)',
                                    'System tools : force stop other applications (S)',
                                    'System tools : format external storage (D)',
                                    'System tools : kill background processes (S)',
                                    'System tools : make application always run (D)',
                                    'System tools : measure application storage space (S)',
                                    'System tools : modify global animation speed (D)',
                                    'System tools : modify global system settings (D)',
                                    'System tools : mount and unmount filesystems (D)',
                                    'System tools : prevent device from sleeping (D)',
                                    'System tools : read subscribed feeds (S)',
                                    'System tools : read sync settings (S)',
                                    'System tools : read sync statistics (S)',
                                    'System tools : read/write to resources owned by diag (S)',
                                    'System tools : reorder running applications (D)',
                                    'System tools : retrieve running applications (D)',
                                    'System tools : send package removed broadcast (S)',
                                    'System tools : send sticky broadcast (S)',
                                    'System tools : set preferred applications (S)',
                                    'System tools : set time zone (D)',
                                    'System tools : set wallpaper (S)',
                                    'System tools : set wallpaper size hints (S)',
                                    'System tools : write Access Point Name settings (D)',
                                    'System tools : write subscribed feeds (D)',
                                    'System tools : write sync settings (D)',
                                    'Your accounts : Google App Engine (D)',
                                    'Your accounts : Google Docs (D)',
                                    'Your accounts : Google Finance (D)',
                                    'Your accounts : Google Maps (D)',
                                    'Your accounts : Google Spreadsheets (D)',
                                    'Your accounts : Google Voice (D)',
                                    'Your accounts : Google mail (D)',
                                    'Your accounts : Picasa Web Albums (D)',
                                    'Your accounts : YouTube (D)',
                                    'Your accounts : YouTube usernames (D)',
                                    'Your accounts : access all Google services (S)',
                                    'Your accounts : access other Google services (D)',
                                    'Your accounts : act as an account authenticator (D)',
                                    'Your accounts : act as the AccountManagerService (S)',
                                    'Your accounts : contacts data in Google accounts (D)',
                                    'Your accounts : discover known accounts (S)',
                                    'Your accounts : manage the accounts list (D)',
                                    'Your accounts : read Google service configuration (S)',
                                    'Your accounts : use the authentication credentials of an account (D)',
                                    'Your accounts : view configured accounts (S)',
                                    'Your location : access extra location provider commands (S)',
                                    'Your location : coarse (network-based) location (D)',
                                    'Your location : fine (GPS) location (D)',
                                    'Your location : mock location sources for testing (D)',
                                    'Your messages : Read Email attachments (D)',
                                    'Your messages : Send Gmail (S)',
                                    'Your messages : edit SMS or MMS (D)',
                                    'Your messages : modify Gmail (D)',
                                    'Your messages : read Gmail (D)',
                                    'Your messages : read SMS or MMS (D)',
                                    'Your messages : read instant messages (D)',
                                    'Your messages : receive MMS (D)',
                                    'Your messages : receive SMS (D)',
                                    'Your messages : receive WAP (D)',
                                    'Your messages : send SMS-received broadcast (S)',
                                    'Your messages : send WAP-PUSH-received broadcast (S)',
                                    'Your personal information : add or modify calendar events and send email to guests (D)',
                                    'Your personal information : choose widgets (S)',
                                    "Your personal information : read Browser's history and bookmarks (D)",
                                    'Your personal information : read calendar events (D)',
                                    'Your personal information : read contact data (D)',
                                    'Your personal information : read sensitive log data (D)',
                                    'Your personal information : read user defined dictionary (D)',
                                    'Your personal information : retrieve system internal state (S)',
                                    'Your personal information : set alarm in alarm clock (S)',
                                    "Your personal information : write Browser's history and bookmarks (D)",
                                    'Your personal information : write contact data (D)',
                                    'Your personal information : write to user defined dictionary (S)']
            features_list = categorical_columns + numerical_columns + binary_encoded_columns
            target_column = ['Class']
            input_feature_train_df = train_df[features_list]
            target_feature_train_df = train_df[target_column]

            input_feature_test_df = test_df[features_list]
            target_feature_test_df = test_df[target_column]
            logging.info('Applying preprocessing object on data')
            processed_train_df = preprocessor_object.fit_transform(input_feature_train_df)
            processed_test_df = preprocessor_object.transform(input_feature_test_df)

            train_arr = np.c_[processed_train_df, np.array(target_feature_train_df)]
            test_arr = np.c_[processed_test_df,np.array(target_feature_test_df)]

            logging.info('saved preprocessed object')

            save_object(file_path = self.data_transformation_config.preprocessor_obj_file_path,
                        obj = preprocessor_object)
            return (train_arr, test_arr,self.data_transformation_config.preprocessor_obj_file_path )
            

        except Exception as e:
            raise CustomException(e,sys)

